- targets:
{% for srv in groups['monitoring'] %}
  {% for prt in hostvars[srv].ports %}
    - "{{ srv }}:{{ prt }}"
  {% endfor%}
{% endfor %}
  labels:
    job: {{ client }}
    client: {{ client }}
